services:
  postgres:
    container_name: postgres_container_emt
    hostname: postgres_container_emt
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: elt_database
      POSTGRES_USER: elt_user
      POSTGRES_PASSWORD: elt_pass
      PGDATA: /data
    volumes:
      - db-postgres:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U elt_user -d elt_database" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-postgres: { }
