springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    admin:
      username: ${APP_ADMIN_USERNAME}
      password: ${APP_ADMIN_PASSWORD}
    user:
      username: ${APP_USER_USERNAME}
      password: ${APP_USER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
